version: '3'

services:
  ansible-control:
    build:
      context: . 
      dockerfile: Dockerfile
    hostname: ansible-control
    volumes:
      - ./cp-ansible:/ansible/ansible_collections/confluent/platform:rw
      - ./inventories:/ansible/inventories
      - ./share:/usr/share/cp-ansible-sandbox
    environment:
      - ANSIBLE_GATHERING=smart
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_RETRY_FILES_ENABLED=False
      - ANSIBLE_COLLECTIONS_PATH=/ansible/ansible_collections
      - ANSIBLE_SSH_PIPELINING=True
      - ANSIBLE_INVENTORY=/ansible/inventories/ansible-inventory.yml
  zookeeper1:
    build:
      context: ./  # This is the directory where your Dockerfile-inventory-node resides
      dockerfile: Dockerfile-inventory-node  # This is the name of your Dockerfile
    hostname: zookeeper1
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2222:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive
  

  kafka1:
    build:
      context: ./  # This is the directory where your Dockerfile-inventory-node resides
      dockerfile: Dockerfile-inventory-node  # This is the name of your Dockerfile
    hostname: kafka1
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2225:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

